Fix i18n dependency load error
conekta/conekta-ruby pull request #108
Opened 2022-04-20 18:38 UTC by juanolivas

[CROSS-258] Fix i18n dependency error

2022-04-20 21:09 UTC, macevedg approved these changes

2022-04-22 13:29 UTC, leofischer requested changes

2022-04-22 13:29 UTC, leofischer commented on conekta.gemspec
> +  spec.add_dependency "i18n"
Por lo que veo solo se requiere esta dependencia en 2 lugares y prefería crear un helper chiquito para removerlo

2022-04-25 17:20 UTC, leofischer approved these changes

2022-04-25 17:42 UTC, merged